import {
  LayoutDashboard,
  Activity,
  Building2,
  Sliders,
  BarChart3,
  Leaf,
  Shield,
  Bell,
  Zap,
  Settings,
  ChevronDown,
  ShieldCheck,
  Users,
  User,
  CreditCard,
  FileText,
  Boxes,
} from 'lucide-react';

export const iconMap: Record<string, any> = {
  LayoutDashboard,
  Activity,
  Building2,
  Sliders,
  BarChart3,
  Leaf,
  Shield,
  Bell,
  Zap,
  Settings,
  ShieldCheck,
  Users,
  User,
  CreditCard,
  FileText,
  ChevronDown,
  Boxes,
  // Aliases for compatibility
  Gauge: Activity,
  Building: Building2,
  Cpu: Activity,
  Hand: Sliders,
  Calendar: Activity,
  DollarSign: BarChart3,
  Calculator: BarChart3,
  Target: BarChart3,
  Database: Activity,
  Layers: BarChart3,
  FileSearch: Shield,
  History: Activity,
  MessageSquare: Bell,
  Plug: Settings,
};
